### ISSUE TITLE
Trouble starting server

### ISSUE THREAD

**Issue by ThePumpkin5822** [RocketMod/Rocket.Unturned#29]
When I try to start the server it says "Steam is up to date" then stops and returns to the terminal. When I use the 'screen -S name' I use 'screen -S Game' and it goes back to the terminal. I have no idea what I'm doing wrong...

**Comment by ThePumpkin5822** [comment]
Really? Not even going to bother? I honestly don't know what I'm doing. I've never used Ubuntu before and I'm going off your very descriptive tutorial.

**Comment by fr34kyn01535** [comment]
This is a bugtracker. The tutorial is a recipe.

**Comment by ThePumpkin5822** [comment]
A very undescriptive one, no one else cares to help. You're the one who made it, how do I do this?

**Comment by fr34kyn01535** [comment]
The recipe is not for people that have no idea what Ubuntu is or how it works. Are you trying this on Ubuntu 14.04? Read the syslog, the unturned log etc. and figure it. I am the one who made it, and who is still working on it, i have no time to help others. I can see you don't understand that, if you want to pay me for the work i will surely look over your issue, otherwise figure it yourself or pay somebody else to work for you. I simply cant deal with anyones issues. It's clearly not a RocketMod bug so it does not belong here.

**Comment by ThePumpkin5822** [comment]
Dick.

**Comment by fr34kyn01535** [comment]
Yea, i know the community is very grateful to me :) You could also just remove RocketMod from your computer, i am sure that would make both of us very happy :P
